cuhacking/atlas

build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/Versions.kt, common/build.gradle.kts, common/src/commonMain/sqldelight/com/cuhacking/atlas/db/Example.sq, gradle/wrapper/gradle-wrapper.properties
The Android Gradle plugin was giving me an error when trying to build, so I had to specify the version of Gradle used in the root folder's`build.gradle.kts` file and the gradle wrapper
=> Add SQLDelight to project

android/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, common/build.gradle.kts
=> Add Spatial K to project

android/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/Versions.kt, common/build.gradle.kts, mapbox/build.gradle.kts
=> Add mapbox sdk

common/src/commonMain/sqldelight/com/cuhacking/atlas/db/Database.sq, common/src/commonMain/sqldelight/com/cuhacking/atlas/db/Example.sq, common/src/commonMain/sqldelight/com/cuhacking/atlas/db/Feature.sq
=> Create feature table & queries

android/build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/Versions.kt, common/build.gradle.kts
commonKdriver causes duplication issues, so currently is not implemented. may not be needed but left in comments, 
closes #6
=> #6 added ktor client to project.

android/build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, common/build.gradle.kts, common/src/androidTest/kotlin/GeoJsonAdapterTest.kt, common/src/commonMain/kotlin/com/cuhacking/atlas/db/GeoJsonAdapter.kt, common/src/commonMain/sqldelight/com/cuhacking/atlas/db/Feature.sq
=> Add GeoJson adapter & test

android/src/main/AndroidManifest.xml, android/src/main/java/com/cuhacking/atlas/AtlasApplication.kt, android/src/main/java/com/cuhacking/atlas/MainActivity.kt, android/src/main/res/layout/activity_main.xml, common/build.gradle.kts, common/src/androidMain/kotlin/com/cuhacking/atlas/common/Example.kt, common/src/androidMain/kotlin/com/cuhacking/atlas/common/MapboxKeyTemp.kt, common/src/commonMain/kotlin/com/cuhacking/atlas/common/Example.kt
=> add map view with random feature

buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/Versions.kt, common/build.gradle.kts, common/src/androidTest/kotlin/DatabaseTest.kt, common/src/commonMain/sqldelight/com/cuhacking/atlas/db/Feature.sq
=> Create FTS table + tests

ios/Podfile, ios/Podfile.lock, ios/atlas.xcodeproj/project.pbxproj
=> Set up ios mapbox sdk

.github/workflows/gradle-check.yml, buildSrc/src/main/kotlin/Versions.kt, common/build.gradle.kts, common/common.podspec, ios/Podfile, ios/Podfile.lock, ios/atlas.xcodeproj/project.pbxproj, mapbox/build.gradle.kts, mapbox/mapbox.podspec
=> Set up Mapbox cocoapod (#3)

ios/atlas.xcodeproj/project.pbxproj, ios/atlas/AppDelegate.swift, ios/atlas/ContentView.swift, ios/atlas/MapView.swift
=> Added map to iOS app

buildSrc/src/main/kotlin/Deps.kt, common/common.podspec, mapbox/mapbox.podspec, server/build.gradle.kts, server/src/main/kotlin/com/cuhacking/atlas/server/DataModule.kt, server/src/main/kotlin/com/cuhacking/atlas/server/Server.kt, server/src/test/kotlin/com/cuhacking/atlas/server/ServerTests.kt, server/src/test/resources/bad.json, server/src/test/resources/data.json, settings.gradle.kts
This is the server we'll be using for the app. It just serves a file you pass it as a command-line argument, and also provides the `Last-Modified` header.
=> Add basic server implementation

.github/workflows/gradle-check.yml, buildSrc/src/main/kotlin/Deps.kt, common/build.gradle.kts, common/src/androidTest/kotlin/FeatureApiTest.kt, common/src/commonMain/kotlin/com/cuhacking/atlas/common/FeatureApi.kt
`server.url=<random url>` should be added in the `local.properties` file for the build to run successfully.'
Resolves #21
=> Add logic for downloading map data into database

.github/workflows/gradle-check.yml, README.md, android/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, buildSrc/src/main/kotlin/Versions.kt
AS 4.2 canary 13 minimum
Targeting Android 11
Targeting iOS 13.7
Upgraded many dependencies
Upgraded to Mapbox SDK 9.5.0 which requires authentication
=> Upgrade various dependencies

android/build.gradle.kts, android/src/androidTest/java/com/cuhacking/atlas/DataCacheTest.kt, build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, common/build.gradle.kts, common/src/androidMain/kotlin/com/cuhacking/atlas/common/DataCache.kt, common/src/androidTest/kotlin/FeatureApiTest.kt, common/src/commonMain/kotlin/com/cuhacking/atlas/common/DataCache.kt, common/src/commonMain/kotlin/com/cuhacking/atlas/common/FeatureApi.kt, common/src/iosMain/kotlin/com/cuhacking/atlas/common/DataCache.kt, common/src/jsMain/kotlin/com/cuhacking/atlas/common/DataCache.kt
=> Add read/write to cache + Android instrumentation test

.dockerignore, .github/workflows/build-server-dev.yml, Dockerfile, build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, gradle/wrapper/gradle-wrapper.properties, server/README.md, server/build.gradle.kts, settings.gradle.kts
Add github action to build a deploy dev server image
Closes #61
=> Add Dockerfile for server

android/build.gradle.kts, android/src/androidTest/java/com/cuhacking/atlas/FeatureApiTest.kt, common/src/androidMain/kotlin/com/cuhacking/atlas/common/DataCache.kt, common/src/androidTest/kotlin/FeatureApiTest.kt, common/src/commonMain/kotlin/com/cuhacking/atlas/common/FeatureApi.kt
=> Update FeatureApi to check for last-modified time + Android Instrumentation test

.github/workflows/build-images.yml, build.gradle.kts, server/Dockerfile, web/Dockerfile
=> Build web image

.github/workflows/gradle-check.yml, .github/workflows/publish.yml, .gitignore, android/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/VersionUtils.kt
* Setup CD for internal testing
* Add app id suffix for debug builds
Closes #84
=> Setup CD for internal testing

build.gradle.kts, gradle/libs.versions.toml, mapbox/src/androidMain/kotlin/com/cuhacking/mapbox/GeoJsonExtensions.kt, mapbox/src/commonMain/kotlin/com/cuhacking/mapbox/layers/Layer.kt, server/build.gradle.kts
=> Upgrade to Kotlin 1.5.10
